FROM node:16-alpine
RUN mkdir -p /home/peng/project/${PROJECT_NAME}-pre
WORKDIR /home/peng/project/${PROJECT_NAME}
COPY package.json /home/peng/project/${PROJECT_NAME}-pre
RUN npm i
COPY . /home/peng/project/${PROJECT_NAME}-pre
EXPOSE ${PROJECT_PORT}
RUN pm2 stop ${PROJECT_NAME}-pre
CMD pm2 start ${PROJECT_NAME}-pre